# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Knock06' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Knock06
  pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git'
  
end
